### ISSUE TITLE
X low and X High in Interpolate Parameter

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/xy_utilities#25]
This:
![image](https://user-images.githubusercontent.com/26659428/103587886-295e6a80-4eb6-11eb-9805-3fc6da092c44.png)

or This:
![image](https://user-images.githubusercontent.com/26659428/103587936-3e3afe00-4eb6-11eb-9990-b7a53c2c112e.png)

Not this:
![image](https://user-images.githubusercontent.com/26659428/103587772-f4eaae80-4eb5-11eb-8288-c2f6850032df.png)

BUT, I think the first two will fail in certain cases like if X is double-valued like a triangle function

**Comment by aditi-nethwewala** [comment]
Yes I did this 

![image](https://user-images.githubusercontent.com/61893772/103594784-a7773d00-4ec7-11eb-8a62-5f430d782ab3.png)
