### ISSUE TITLE
Linear Fit

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/xy_utilities#29]

**Comment by ciozi137** [comment]
https://forums.ni.com/t5/LabVIEW/Least-squares-fit-alternative/td-p/3837458

**Comment by ciozi137** [comment]
#30

**Comment by aa-greenberg** [comment]
Did you push the build to VIPM? I don't see it there.

**Comment by ciozi137** [comment]
Not yet...maybe 15 minutes

**Comment by ciozi137** [comment]
@aa-greenberg v1.3.0 built and posted. You can start trying to refresh, but sometimes it takes up to ~10 minutes for the index to refresh
